### ISSUE TITLE
`Server error: u128 is not supported`

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#1076]
I am using `nearlib` to query nearcore RPC and at least one out of 1k concurrent requests to `block` RPC endpoint fails with the following error:

```
Error: [-32000] Server error: u128 is not supported
    at JsonRpcProvider.sendJsonRpc (/near.ai/near-explorer/backend/node_modules/nearlib/lib/providers/json-rpc-provider.js:50:19)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Basically, I fetch all the blocks one by one (I maintain 1k concurrent requests).

I cannot reproduce this bug in a non-concurrent environment, so it must be something racy going on.

I can extract the JS reproduction code if necessary.

**Comment by frol** [comment]
@ilblackdragon The new testnet still has this issue:

```
http post https://rpc.nearprotocol.com/ jsonrpc=2.0 method=block params:="[194138]" id="dontcare"
HTTP/1.1 200 OK
Alt-Svc: clear
Via: 1.1 google
content-length: 113
content-type: application/json
date: Mon, 12 Aug 2019 12:41:19 GMT

{
    "error": {
        "code": -32000,
        "data": "u128 is not supported",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

**Comment by evgenykuzyakov** [comment]
@ilblackdragon Is it still an issue?

**Comment by ilblackdragon** [comment]
Fixed.
