### ISSUE TITLE
No Task running crash in Actix

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1080]
Running non-validating node for weeks lead to this:
```
thread 'main' panicked at 'no Task is currently running', /home/illia_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:47:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Panic in Arbiter thread, shutting down system.
thread 'main' panicked at 'no Task is currently running', /home/illia_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:47:9
stack backtrace:
   0:     0x55af33d1fc88 - backtrace::backtrace::libunwind::trace::h8ed5d9ae1d8037d0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x55af33d1fc88 - backtrace::backtrace::trace_unsynchronized::h2c3e43c5cb83cbee
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x55af33d1fc88 - std::sys_common::backtrace::_print::h621b9f6822ef2d33
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55af33d1fc88 - std::sys_common::backtrace::print::h6edc8d6ecd0550e9
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55af33d1fc88 - std::panicking::default_hook::{{closure}}::hac736251a65c7a5c
                               at src/libstd/panicking.rs:198
   5:     0x55af33d1f3e8 - std::panicking::default_hook::he803cdbf34b9db7d
                               at src/libstd/panicking.rs:212
   6:     0x55af33d1f3e8 - std::panicking::rust_panic_with_hook::h335228e51d0b7420
                               at src/libstd/panicking.rs:475
   7:     0x55af33d1da24 - std::panicking::begin_panic::h54d9870fc619ca57
   8:     0x55af33d0efd7 - tokio_sync::task::atomic_task::AtomicTask::register::hd53fd9ff43a7267e
   9:     0x55af33d09fe5 - tokio_reactor::registration::Registration::poll_ready::h5a5716d3872c24d7
  10:     0x55af33cefd69 - tokio_reactor::poll_evented::PollEvented<E>::poll_write_ready::h333ff52f42009ecd
  11:     0x55af33cf0194 - <tokio_tcp::stream::TcpStream as std::io::Write>::write::hcae8f0625917d192
  12:     0x55af33950946 - <tokio_io::split::WriteHalf<T> as std::io::Write>::write::hc6deb74a85eb046e
  13:     0x55af33982f50 - core::ptr::real_drop_in_place::h747eaf76307d8f87
  14:     0x55af33983230 - core::ptr::real_drop_in_place::h12e9ad5002f453d0
  15:     0x55af3398350f - core::ptr::real_drop_in_place::h4b9f17b802f61e49
  16:     0x55af33cf8724 - tokio_current_thread::scheduler::release_node::h08036790cb0e1d57
  17:     0x55af33cfa94a - core::ptr::real_drop_in_place::h506745254e60f1d1
  18:     0x55af33600853 - near::main::hd59043545b12dac4
  19:     0x55af335e95c3 - std::rt::lang_start::{{closure}}::h7e9552e511b6955e
  20:     0x55af3360162e - main
  21:     0x7fb470e8cb97 - __libc_start_main
  22:     0x55af335e94da - _start
  23:                0x0 - <unknown>
thread panicked while panicking. aborting.
```

**Comment by ailisp** [comment]
Did some initial search, found this kind of error is usually running future outside of an executor. Is it possible to run with RUST_BACKTRACE=1 to get more backtrace?

**Comment by ilblackdragon** [comment]
I think at this point let's close it as we have not observed this for awhile.
