### ISSUE TITLE
"Panic in Arbiter thread"

### ISSUE THREAD

**Issue by frol** [nearprotocol/nearcore#1133]
I have just run a new testnet node in Docker [19.03.1-ce] on my laptop [Arch Linux, x64] and after 95% of "Downloading headers" I started getting this crash and it is reproducible on every boot, i.e. I cannot get the node running as it just keeps crashing after a few seconds:

```
[2019-08-02T15:15:56Z INFO  near_network::peer_manager] Server listening at xxx@0.0.0.0:24567
[2019-08-02T15:16:06Z INFO  near_client::client] #       0 Downloading headers 100% -/4 10/1/40 peers ⬇ 16 B/s ⬆ 9 B/s 0.00 bls 0.00 tps
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:211
             at src/libstd/panicking.rs:474
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   4: rust_begin_unwind
             at src/libstd/panicking.rs:308
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::panicking::panic
             at src/libcore/panicking.rs:49
   7: near::validator_manager::ValidatorManager::finalize_epoch
   8: <near::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::add_validator_proposals
   9: <near_client::client::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  10: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  11: <actix::contextimpl::ContextFut<A,C> as futures::future::Future>::poll
  12: actix_rt::runtime::Runtime::block_on
  13: near::main
  14: std::rt::lang_start::{{closure}}
  15: main
  16: __libc_start_main
  17: _start
Panic in Arbiter thread, shutting down system.
```

P.S. I had to manually edit the `scripts/nearlib.py` to add `RUST_BACKTRACE=1`. We should consider a better bug reporting experience.

**Comment by bowenwang1996** [comment]
Looks like something in validator manager went wrong. @ilblackdragon is rewriting it and also the code in docker is old.

**Comment by evgenykuzyakov** [comment]
Can we close it?

**Comment by evgenykuzyakov** [comment]
@ilblackdragon

**Comment by nearmax** [comment]
This is still happening. Happened twice on CI today.

**Comment by ilblackdragon** [comment]
Let's close this as we haven't seen this.
