### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/nearcore#1521]
Coredump is on near1
```
thread 'main' panicked at 'no Task is currently running', /home/illia_nearprotocol_com/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.28/src/task_impl/mod.rs:47:9
stack backtrace:
   0:     0x559806827403 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h8f3e269988de8149
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x5598068258a1 - std::panicking::default_hook::{{closure}}::h7d4a222b68bf0690
                               at src/libstd/sys_common/backtrace.rs:71
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   2:     0x559806824704 - std::panicking::rust_panic_with_hook::h2796b955a37c6939
                               at src/libstd/panicking.rs:211
                               at src/libstd/panicking.rs:474
   3:     0x559806822a33 - std::panicking::begin_panic::haf45a5ae7d19e728
   4:     0x559806813f3c - tokio_sync::task::atomic_task::AtomicTask::register::h9827e2a71a583c24
   5:     0x55980680eef0 - tokio_reactor::registration::Registration::poll_ready::h533e976e60fa732d
   6:     0x5598067f4773 - tokio_reactor::poll_evented::PollEvented<E>::poll_write_ready::he07aa347d7eff1bc
   7:     0x5598067f4bb3 - <tokio_tcp::stream::TcpStream as std::io::Write>::write::h46513b128bf34d5d
   8:     0x5598063c12c5 - <tokio_io::split::WriteHalf<T> as std::io::Write>::write::h13bc76581d821eaa
   9:     0x55980645d53a - core::ptr::real_drop_in_place::ha39f73d314e39506
  10:     0x55980645db8f - core::ptr::real_drop_in_place::h1d4ec06953d431ad
  11:     0x55980645dace - core::ptr::real_drop_in_place::hf93c5e615493024b
  12:     0x5598067fdae3 - tokio_current_thread::scheduler::release_node::hae4cc7dc965f0451
  13:     0x5598067fd9ee - core::ptr::real_drop_in_place::h5f07efa40ce142aa
  14:     0x5598067fa94d - actix_rt::runtime::Runtime::block_on::h9372794f3742ffb3
  15:     0x559805e04aa4 - near::main::h503a41b96348d60f
  16:     0x559805dee0d2 - std::rt::lang_start::{{closure}}::h726edf622d44d1b8
  17:     0x559805e0830d - main
  18:     0x7fd491099b96 - __libc_start_main
  19:     0x559805dedfe9 - _start
  20:                0x0 - <unknown>
Panic in Arbiter thread, shutting down system.
```

**Comment by ilblackdragon** [comment]
@bowenwang1996 @ailisp have we seen this recently?

**Comment by bowenwang1996** [comment]
I still sometimes see this.

**Comment by damons** [comment]
Any news on this?

**Comment by ailisp** [comment]
Have difficulties to reproduce this and understand the root cause

**Comment by bowenwang1996** [comment]
We still don't quite understand what happened there.

**Comment by damons** [comment]
Unless we can get steps to reproduce, this shouldn't block mainnet.   Just FYI:  I'm going through all open issues for nearcore, wallet, and explorer to identify and mark mainnet hard blockers.

**Comment by ilblackdragon** [comment]
Let's close this if we can't reproduce given it's been awhile.
