### ISSUE TITLE
start_localnet.py EOFError

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/nearcore#1608]
During the Rust in Blockchain workshop of SFBW19 one person observed the following bug that prevented them from running a node:
```
~/Desktop/SFBW/nearcore$ sudo ./scripts/start_localnet.py
[sudo] password for ettares:
****************************************************
* Running NEAR validator node for Local TestNet    *
****************************************************
^@^BcSetting up network configuration.
Enter your account ID: kgoodall
Traceback (most recent call last):
  File "./scripts/start_localnet.py", line 28, in <module>
    setup_and_run(nodocker, not args.debug, args.image, args.home, ['--chain-id='], '', args.verbose)
  File "/home/ettares/Desktop/SFBW/nearcore/scripts/nodelib.py", line 175, in setup_and_run
    check_and_setup(nodocker, is_release, image, home_dir, init_flags)
  File "/home/ettares/Desktop/SFBW/nearcore/scripts/nodelib.py", line 86, in check_and_setup
    account_id = input(prompt)
EOFError
```

**Comment by ilblackdragon** [comment]
@nearmax The user did ^@^Bc after entering password for sudo. Hence the EOFError.
