### ISSUE TITLE
staking invariant does not hold.Account stake 0 is less than maximum of stakes 

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#1612]
```
thread 'main' panicked at 'FATAL: staking invariant does not hold.Account stake 0 is less than maximum of stakes 50000000000000000000000000 in the past three epochs', runtime/runtime/src/lib.rs:877:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:335
  13: node_runtime::Runtime::apply
  14: near::runtime::NightshadeRuntime::process_state_update
  15: <near::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
  16: near_chain::types::RuntimeAdapter::apply_transactions
  17: near_chain::chain::ChainUpdate::apply_chunks
  18: near_chain::chain::Chain::process_block_single
  19: near_client::client_actor::ClientActor::process_block
  20: near_client::client_actor::ClientActor::block_production_tracking
  21: <actix::utils::TimerFunc<A> as actix::fut::ActorFuture>::poll
  22: <actix::contextimpl::ContextFut<A,C> as futures::future::Future>::poll
  23: actix_rt::runtime::Runtime::block_on
  24: near::main
  25: std::rt::lang_start::{{closure}}
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in Arbiter thread, shutting down system.
```

Imo:
1. is it possible to step down as non validator in this case, instead of crash?
2. the wording, should it be "is less than minimum of stakes"

**Comment by bowenwang1996** [comment]
This is related to challenges. Looks like some rollback is not done properly, but otherwise the invariant should never fail.
