### ISSUE TITLE
Sent using near send shows error, but shown as successful in explorer

### ISSUE THREAD

**Issue by sweetpotatoz** [nearprotocol/nearcore#1722]
## Story

```
near send validators_online jleony 1000000000000000000
[WARNING] Didn't find config at /home/<id>/src/config, using default shell config
{ networkId: 'tatooine',
  nodeUrl: 'https://rpc.tatooine.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.tatooine.nearprotocol.com' }
Sending 1000000000000000000 NEAR to jleony from validators_online
Error:  { Error: send_tx_commit has timed out
    at JsonRpcProvider.sendJsonRpc (/usr/lib/node_modules/near-shell/node_modules/nearlib/lib/providers/json-rpc-provider.js:60:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) type: 'TimeoutError' }

error as above, but shown as successful in explorer   
    https://explorer.tatooine.nearprotocol.com/transactions/B1Xx632yEyAjzm9CXYz1wuzfdqEShyQJ6afRvvUUFFG5
```

balance in wallet GUI is updated as like the transfer was successful

near send was run in home folder where i have neardev folder that contain private key for validatrs_online id

**Comment by vgrichina** [comment]
Transfer was indeed successful, `send_tx_commit has timed out` is a symptom of network running slow.
