### ISSUE TITLE
Panic on running from staging branch

### ISSUE THREAD

**Issue by k06a** [nearprotocol/nearcore#1968]
I first erased `neardir` directory and launched `cargo run --package near --bin near -- --home /Users/zaver/Projects/nearcore/testdir init --chain-id= --test-seed=alice.near --account-id=test.near --fast` in Clion and it succeded

Then I launched `cargo run --package near --bin near -- --home /Users/zaver/Projects/nearcore/testdir run --boot-nodes=` and got panic:

```
/Users/k06a/Projects/nearcore/target/debug/near --home /Users/k06a/Projects/nearcore/testdir run --boot-nodes=
Jan 16 02:10:18.583  INFO near: Did not find "/Users/k06a/Projects/nearcore/testdir/data" path, will be creating new store database    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 48, kind: AddrInUse, message: "Address already in use" }', src/libcore/result.rs:1165:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/liballoc/boxed.rs:924
   6: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:69
   7: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   8: std::panicking::continue_panic_fmt
   9: std::panicking::try::do_call
  10: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  11: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  12: core::result::Result<T,E>::unwrap
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/result.rs:933
  13: near_jsonrpc::start_http
             at chain/jsonrpc/src/lib.rs:417
  14: near::start_with_config
             at near/src/lib.rs:101
  15: near::main
             at near/src/main.rs:160
  16: std::rt::lang_start::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  17: std::panicking::try::do_call
  18: panic_unwind::dwarf::eh::read_encoded_pointer
  19: std::panicking::update_count_then_panic
  20: std::rt::lang_start
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/rt.rs:64
  21: near::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'no current timer', src/libcore/option.rs:1190:5
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/liballoc/boxed.rs:924
   6: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:69
   7: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   8: std::panicking::continue_panic_fmt
   9: std::panicking::try::do_call
  10: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  11: core::option::expect_failed
             at src/libcore/option.rs:1190
  12: <usize as core::ops::arith::Sub>::sub
  13: tokio::time::driver::handle::Handle::current
  14: tokio::time::driver::registration::Registration::new
  15: tokio::sync::semaphore_ll::WaiterState::is_dropped
  16: tokio::sync::semaphore_ll::WaiterState::is_dropped
  17: actix::utils::TimerFunc<A>::new
             at /Users/k06a/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/utils.rs:102
  18: actix::actor::AsyncContext::run_later
             at /Users/k06a/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/actor.rs:453
  19: near_client::client_actor::ClientActor::sync
             at chain/client/src/client_actor.rs:1002
  20: near_client::client_actor::ClientActor::start_sync
             at chain/client/src/client_actor.rs:820
  21: <near_client::client_actor::ClientActor as actix::actor::Actor>::started
             at chain/client/src/client_actor.rs:120
  22: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
             at /Users/k06a/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/contextimpl.rs:348
  23: <actix::contextimpl::ContextFut<A,C> as core::ops::drop::Drop>::drop
             at /Users/k06a/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/contextimpl.rs:228
  24: core::ptr::real_drop_in_place
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/ptr/mod.rs:175
  25: core::ptr::real_drop_in_place
  26: core::ptr::real_drop_in_place
  27: core::ptr::real_drop_in_place
  28: <tokio::time::clock::Clock as core::clone::Clone>::clone
  29: core::ptr::real_drop_in_place
  30: core::ptr::real_drop_in_place
  31: core::ptr::real_drop_in_place
  32: core::ptr::real_drop_in_place
  33: <tokio::runtime::thread_pool::spawner::Spawner as core::clone::Clone>::clone
  34: core::ptr::swap_nonoverlapping_bytes
  35: std::sys::unix::fast_thread_local::register_dtor::run_dtors
  36: <unknown>
  37: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Signal: SIGABRT (signal SIGABRT)
```

**Comment by bowenwang1996** [comment]
It says what the error is. You probably have another instance running at the same time.

**Comment by k06a** [comment]
@bowenwang1996 thanks, not recognized error message, now it's clear to me issue was about already used port, yep docker launched some container after system reboot.
