### ISSUE TITLE
Fix nightly tests failure reporting

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearcore#2347]
Many nightly testes fail with
```
Traceback (most recent call last):
  File "/home/bo_nearprotocol_com/nightly/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/bo_nearprotocol_com/nightly/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/bo_nearprotocol_com/nightly/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```
And we have to checkout the logs to see the actual failure, which is quite annoying. It could be a problem with the nightly test infrastructure.

**Comment by ailisp** [comment]
The real fail is one of node.get_status() call fails, however, I couldn't reproduce this fail locally after checkout:
https://nightly.neartest.com/run/d64a3b31d6175362e2040ebd2e2ae4c4ab08f5c7_200402_104127/pytest/pytest_sanity_garbage_collection1_py/stderr
https://nightly.neartest.com/run/d64a3b31d6175362e2040ebd2e2ae4c4ab08f5c7_200402_104127/pytest/pytest_adversarial_start_from_genesis_py_doomslug_off/stderr
https://nightly.neartest.com/run/d64a3b31d6175362e2040ebd2e2ae4c4ab08f5c7_200402_104127/pytest/pytest_adversarial_start_from_genesis_py_overtake_doomslug_off/stderr

**Comment by bowenwang1996** [comment]
It feels like it might be related to the runner because I also haven't seen this locally.

**Comment by ailisp** [comment]
Seems don't happen recently, closed
