### ISSUE TITLE
TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by sl-he** [nearprotocol/nearcore#2605]
**Describe the bug**
I try to run **near state MY_ADDRESS** in shell script

**To Reproduce**
1. start **source $HOME/.nearup/env && neadr state MY_ADDRESS**
2. See an error

**Expected behavior**
Well, I expected them to display the status of my address, but not that.

**Version (please complete the following information):**
- near shell 0.21.0
- betanet

**Additional context**
/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:4
const { readFile, writeFile } = require('fs').promises;
        ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:4:46)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/bin/near-cli.js:189:14)
    at Module._compile (module.js:652:30)

**Comment by bowenwang1996** [comment]
This issue should probably be transferred to https://github.com/near/near-shell but github does not allow cross-organization transfer. cc @vgrichina

**Comment by sl-he** [comment]
Moved https://github.com/near/near-shell/issues/345
