### ISSUE TITLE
Storage Error: StorageInconsistentState panic during the initial node synchronization

### ISSUE THREAD

**Issue by k0kk0k** [nearprotocol/nearcore#2695]
OS: Ububntu 18.04
NEAR:  version: 0.4.13, build:2d02b333
exec: `nearup betanet --nodocker`
```
May 21 05:06:08.636  INFO stats: # 5592805 Downloading headers 87% -/58 10/10/40 peers ⬇ 448.5kiB/s ⬆ 12.7kiB/s 0.00 bps 0 gas/s CPU: 89%, Mem: 330.3 MiB
May 21 05:06:19.585  INFO stats: # 5592805 Downloading headers 88% -/58 10/10/40 peers ⬇ 397.9kiB/s ⬆ 41.7kiB/s 0.00 bps 0 gas/s CPU: 113%, Mem: 333.1 MiB
May 21 05:06:33.092  INFO stats: # 5592805 Downloading headers 90% -/58 10/10/40 peers ⬇ 472.4kiB/s ⬆ 43.1kiB/s 0.00 bps 0 gas/s CPU: 90%, Mem: 333.6 MiB
May 21 05:06:43.094  INFO stats: # 5592805 Downloading headers 92% -/58 10/10/40 peers ⬇ 505.9kiB/s ⬆ 44.4kiB/s 0.00 bps 0 gas/s CPU: 79%, Mem: 334.1 MiB
May 21 05:06:55.342  INFO stats: # 5592805 Downloading headers 92% -/58 10/9/40 peers ⬇ 473.0kiB/s ⬆ 45.1kiB/s 0.00 bps 0 gas/s CPU: 36%, Mem: 334.1 MiB
May 21 05:07:05.345  INFO stats: # 5592805 Downloading headers 93% -/58 10/10/40 peers ⬇ 504.1kiB/s ⬆ 46.6kiB/s 0.00 bps 0 gas/s CPU: 45%, Mem: 334.1 MiB
May 21 05:07:08.423 ERROR network: Attempting to connect to a node (ed25519:2qccg3Qo8Xr3SPttk6aaB334euZMXmiACTWWnhyMBzUS@0.0.0.0:24567@c29r3) with a different genesis block. Our genesis: GenesisId { chain_id: "betanet", hash: `5f946JMoMEbv4P2kt6bdTbrTwPxzcijD99UZHxd44cY3` }, their genesis: GenesisId { chain_id: "betanet", hash: `4bheNjvxrPhnvNhcPcoPdECmzzEXPSxwTrGNTz7kmBqh` }
May 21 05:07:18.704  INFO stats: # 5592805 Downloading headers 94% -/58 10/10/40 peers ⬇ 444.8kiB/s ⬆ 17.9kiB/s 0.00 bps 0 gas/s CPU: 60%, Mem: 334.1 MiB
May 21 05:07:28.708  INFO stats: # 5592805 Downloading headers 96% -/58 10/10/40 peers ⬇ 440.6kiB/s ⬆ 17.1kiB/s 0.00 bps 0 gas/s CPU: 81%, Mem: 334.1 MiB
May 21 05:07:41.392  INFO stats: # 5592805 Downloading headers 98% -/58 10/10/40 peers ⬇ 437.7kiB/s ⬆ 16.1kiB/s 0.00 bps 0 gas/s CPU: 92%, Mem: 334.9 MiB
May 21 05:07:45.407  INFO telemetry: Telemetry data could not be sent due to: Failed to connect to host: Timeout out while establishing connection
May 21 05:07:51.394  INFO stats: # 5592805 Downloading headers 99% -/58 10/10/40 peers ⬇ 474.4kiB/s ⬆ 17.6kiB/s 0.00 bps 0 gas/s CPU: 45%, Mem: 339.8 MiB
May 21 05:08:07.248  INFO stats: State [0: header] -/58 10/9/40 peers ⬇ 441.5kiB/s ⬆ 18.1kiB/s 0.00 bps 0 gas/s CPU: 70%, Mem: 505.8 MiB
May 21 05:08:17.249  INFO stats: State [0: parts] -/58 11/10/40 peers ⬇ 593.2kiB/s ⬆ 47.3kiB/s 0.00 bps 0 gas/s CPU: 72%, Mem: 533.2 MiB

thread 'main' panicked at 'Storage Error: StorageInconsistentState("Trie node missing")
 Cause: Unknown
 Backtrace:    0: failure::backtrace::Backtrace::new
   1: neard::runtime::NightshadeRuntime::process_state_update
   2: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
   3: near_chain::types::RuntimeAdapter::apply_transactions
   4: near_chain::chain::ChainUpdate::apply_chunks
   5: near_chain::chain::Chain::process_block_single
   6: near_client::client_actor::ClientActor::process_block
   7: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
   8: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
   9: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  10: tokio::runtime::task::raw::poll
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
  12: actix_rt::runtime::Runtime::block_on
  13: near::main
  14: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at src/libstd/sys_common/backtrace.rs:130
  15: main
  16: __libc_start_main
  17: _start
', neard/src/runtime.rs:901:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  14: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
  15: near_chain::types::RuntimeAdapter::apply_transactions
  16: near_chain::chain::ChainUpdate::apply_chunks
  17: near_chain::chain::Chain::process_block_single
  18: near_client::client_actor::ClientActor::process_block
  19: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  20: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  21: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  22: tokio::runtime::task::raw::poll
  23: <std::future::GenFuture<T> as core::future::future::Future>::poll
  24: actix_rt::runtime::Runtime::block_on
  25: near::main
  26: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
May 21 04:35:23.823 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:BfpM534pXYeaj39RsWvd9r2qDqFgqjj5HeNJzbop2x6y@161.35.194.190:24567)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', neard/src/../src/main.rs:201:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: rust_begin_unwind
             at src/libstd/panicking.rs:419
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by bowenwang1996** [comment]
@mikhailOK @Kouprin I thought this is fixed?

**Comment by bowenwang1996** [comment]
Actually this backtrace looks very suspicious. I don't see how it is possible that while in state sync,  the node can process some incoming block. The block should be orphaned in this case.

**Comment by sl-he** [comment]
You have closed my Issue, but how do I sync my node? It constantly reboots cyclically.

**Comment by bowenwang1996** [comment]
@sl-he I closed it because of duplication, not because we have resolved it.

**Comment by bowenwang1996** [comment]
Fixed in https://github.com/nearprotocol/nearcore/pull/2762
