### ISSUE TITLE
near-vm-runner memory panicked at .expect("TODO creating memory cannot fail")

### ISSUE THREAD

**Issue by khorolets** [nearprotocol/nearcore#3118]
**Describe the bug**
I had the running [NEAR Indexer for Wallet](https://github.com/near/near-indexer-for-wallet) for testnet. Unexpectedly it crashed with error on this line.
https://github.com/nearprotocol/nearcore/blob/master/runtime/near-vm-runner/src/memory.rs#L20

```
thread 'main' panicked at 'TODO creating memory cannot fail: UnableToCreateMemory', /usr/local/cargo/git/checkouts/nearcore-e3f14b9758bedfa0/f80c127/runtime/near-vm-runner/src/memory.rs:12:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: near_vm_runner::memory::WasmerMemory::new
  16: near_vm_runner::wasmer_runner::run_wasmer
  17: near_vm_runner::runner::run
  18: node_runtime::actions::action_function_call
  19: node_runtime::Runtime::apply_action_receipt
  20: node_runtime::Runtime::apply::{{closure}}
  21: node_runtime::Runtime::apply
  22: neard::runtime::NightshadeRuntime::process_state_update
  23: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
  24: near_chain::types::RuntimeAdapter::apply_transactions
  25: near_chain::chain::ChainUpdate::apply_chunks
  26: near_chain::chain::ChainUpdate::process_block
  27: near_chain::chain::Chain::process_block_single
  28: near_chain::chain::Chain::check_blocks_with_missing_chunks
  29: near_client::client::Client::process_blocks_with_missing_chunks
  30: near_client::client::Client::process_partial_encoded_chunk
  31: near_client::client::Client::process_partial_encoded_chunk_response
  32: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  33: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  34: actix::mailbox::Mailbox<A>::poll
  35: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  36: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  37: tokio::runtime::task::harness::Harness<T,S>::poll
  38: std::thread::local::LocalKey<T>::with
  39: tokio::task::local::LocalSet::tick
  40: tokio::macros::scoped_tls::ScopedKey<T>::set
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  42: std::thread::local::LocalKey<T>::with
  43: tokio::macros::scoped_tls::ScopedKey<T>::set
  44: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on                                                                                                                             
  45: tokio::runtime::context::enter
  46: actix_rt::builder::SystemRunner::run
  47: near_indexer::Indexer::start
  48: near_indexer_for_wallet::main
  49: std::rt::lang_start::{{closure}}
  50: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  51: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  52: std::panicking::try
             at src/libstd/panicking.rs:274
  53: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  54: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  55: main
  56: __libc_start_main
  57: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', /usr/local/cargo/git/checkouts/nearcore-e3f14b9758bedfa0/f80c127/chain/
indexer/src/lib.rs:74:9
stack backtrace:
0: backtrace::backtrace::libunwind::trace                                                                                                                                                   [10/1933]
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: near_indexer::Indexer::start
  16: near_indexer_for_wallet::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  20: std::panicking::try
             at src/libstd/panicking.rs:274
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
```

**To Reproduce**
It was running days before the crash, unfortunately I don't know how to reproduce it again

**Version (please complete the following information):**
- testnet

/cc @frol

**Comment by bowenwang1996** [comment]
This is expected when your node runs out of memory. Please let me know if you have any other concerns.

**Comment by khorolets** [comment]
I've faced this issue couple of times already, using the machine when RAM usage were 14.1 GiB. I wonder if it is a memory? Is this issue should be reopened or someone can point me to corresponding one?

/cc @bowenwang1996 @frol
