### ISSUE TITLE
rpc: schedule function call not compatible with py2

### ISSUE THREAD

**Issue by azban** [nearprotocol/nearcore#429]
```
./scripts/rpc.py schedule_function_call test_contract add --args '{"a": 10, "b": 20}'
Traceback (most recent call last):
  File "./scripts/rpc.py", line 619, in <module>
    MultiCommandParser()
  File "./scripts/rpc.py", line 372, in __init__
    response = getattr(self, args.command)()
  File "./scripts/rpc.py", line 531, in schedule_function_call
    args.args,
  File "./scripts/rpc.py", line 226, in schedule_function_call
    args = list(bytearray(args))
TypeError: string argument without an encoding
```

**Comment by evgenykuzyakov** [comment]
@azban Is this still an issue?

**Comment by azban** [comment]
nope
