### ISSUE TITLE
Flaky error

### ISSUE THREAD

**Issue by evgenykuzyakov** [nearprotocol/nearcore#927]
```
 Full response: {"jsonrpc":"2.0","id":"1556309516276","error":{"code":-32603,"message":"Internal error","data":"Tx (689B0032E949B9D5D56D8C97D532D429ACFF6F18D57D0BD10E76D275D6329221) not found"}}
```
Happens frequently for nearlib promise tests
Also happens when you trying to deploy:
```
Error:  Error: Error calling tx with VkJ4FS+i+F0DdxjkoeKYM37JrCZhUxxGr0ZftUdRTas=,false: Internal error.
Full response: {"jsonrpc":"2.0","id":"1556318494372","error":{"code":-32603,"message":"Internal error","data":"Tx (564278152FA2F85D037718E4A1E298337EC9AC2661531C46AF465FB547514DAB) not found"}}
    at NearClient.jsonRpcRequest (/Users/vg/Documents/near-place/node_modules/nearlib/nearclient.js:84:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Best way to reproduce is to run `npm test` in nearlib

This issue is bad enough in general, but also blocks us from re-enabling nearlib CI

**Comment by evgenykuzyakov** [comment]
cc @vgrichina

**Comment by bowenwang1996** [comment]
I tried a couple times but cannot reproduce this locally.

**Comment by evgenykuzyakov** [comment]
Do you mean nearlib always passes all tests?

**Comment by bowenwang1996** [comment]
Yes

**Comment by evgenykuzyakov** [comment]
Let's re-enable CI for nearlib then to see if it's flaky on CI

**Comment by bowenwang1996** [comment]
Working on it #925

**Comment by ilblackdragon** [comment]
Power to 2.0
