### ISSUE TITLE
Better error message for duplicate account creation

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/nearcore#978]
Current message doesn't provide any info:

```
Error:  { BadRequestError: Transaction kMOqXImoOFwuo/vyzj0LwRdf9NUehwJ68vYD6z3rJIE= on unknown contract failed. 
    at sendJson (/Users/vg/Documents/nearlib/internal/send-json.js:12:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Transaction kMOqXImoOFwuo/vyzj0LwRdf9NUehwJ68vYD6z3rJIE= on unknown contract failed. ' }
```

**Comment by ilblackdragon** [comment]
@evgenykuzyakov is this still an issue?

**Comment by nearmax** [comment]
@evgenykuzyakov ping

**Comment by nearmax** [comment]
@fckt Is this fixed?

**Comment by fckt** [comment]
Just checked. It yields the following now:
```
Error:  TypedError: Transaction Dg8TdgKe2ZhJnGnkWgAiHSFng1tQBnCDKqSxGJx3wuDT failed. Can't create a new account nead, because it already exists
```
